<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="MartinCostello.Logging.XUnit.v3" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Testcontainers.Kafka" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Steelax.Pufflow.Operators.Kafka\Steelax.Pufflow.Operators.Kafka.csproj" />
      <ProjectReference Include="..\..\src\Steelax.Pufflow.Test.Sdk.Kafka\Steelax.Pufflow.Test.Sdk.Kafka.csproj" />
      <ProjectReference Include="..\..\src\Steelax.Pufflow.Test.Sdk\Steelax.Pufflow.Test.Sdk.csproj" />
    </ItemGroup>

</Project>
